name: build and test code
on:
   push:
    branchs:
         - main
   workflow_dispatch:      
jobs:
     build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: download dependency    
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin' 
                java-version: '17'

            - name: pacakge the code
              run: mvn clean install -DskipTests

            - name: upload artifacts
              uses: actions/upload-artifact@v3
              with:
               name: my-artifact
               path: ~/**/target/*.war
                  
     test:
        needs: build
        runs-on: ubuntu-latest
        steps:  
         - name: checkout
           uses: actions/checkout@v3

         - name: download dependency    
           uses: actions/setup-java@v3
           with:
             distribution: 'temurin' 
             java-version: '17'     
         - name: test the code  
           run: mvn test



                  
